### ISSUE TITLE
prototipo practica#1

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practicaprototipos-topicos4semestre2022#3]
[PROTOTIPADO DE TOPIDOS DISEÑO PRACTICA 1.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-topicos4semestre2022/files/8191907/PROTOTIPADO.DE.TOPIDOS.DISENO.PRACTICA.1.pdf)

**Comment by josealfredo79** [comment]
Y la calificacion...falta

**Comment by JudithReynaCS** [comment]
calificacion:17

**Comment by josealfredo79** [comment]
Bien hecho y revisado
